spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: hadoop
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 8.142.140.110
    database: 0
    port: 16379
    password: 56^^78!90
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/